/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-west-1",
  aws_cognito_identity_pool_id:
    "eu-west-1:5d48b29d-b712-4d29-814d-f1c6124abbcf",
  aws_cognito_region: "eu-west-1",
  aws_user_pools_id: "eu-west-1_sNBTcPbi9",
  aws_user_pools_web_client_id: "7d0dtvj8je5kpgn8jrc9c2mjj0",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://boj5uowajjg53h7w4gqmwts2uu.appsync-api.eu-west-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-west-1",
  aws_appsync_authenticationType: "AWS_IAM",
};

export default awsmobile;
