/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:fe88ceac-5b75-47de-9e85-ce79aced953b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_ovM8qQiKB",
    "aws_user_pools_web_client_id": "774mv8vhst9vvlf7cn8bkuhc7p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://boj5uowajjg53h7w4gqmwts2uu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AWS_IAM"
};


export default awsmobile;
